version: "3.7"

services:
  scheduler:
    image: docker.uncharted.software/worldmodeler/wm-data-pipeline:latest
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "2"
    hostname: dask-scheduler
    networks:
      - prefect-server
      - dask
    ports:
      - "8786:8786"
      - "8787:8787"
    command: ["dask-scheduler"]

  worker:
    image: docker.uncharted.software/worldmodeler/wm-data-pipeline:latest
    deploy:
      replicas: 3
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "2"
    hostname: dask-worker
    networks:
      - dask
    command: ["dask-worker", "tcp://scheduler:8786"]

networks:
  prefect-server:
    name: prefect-server
  dask:
    name: dask