version: "3.7"

services:
  scheduler:
    image: docker.uncharted.software/worldmodeler/wm-dask-server:latest
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "2"
    hostname: dask-scheduler
    ports:
      - "8786:8786"
      - "8787:8787"
    command: ["dask-scheduler"]

  worker:
    image: docker.uncharted.software/worldmodeler/wm-dask-server:latest
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "2"
    hostname: dask-worker
    command: ["dask-worker", "tcp://scheduler:8786"]
